"""Writer for the lwe-engine.service unit + its environment file.

The two-service architecture's mechanism half: the engine becomes a first-class
systemd user daemon (`--daemon` idle boot, socket control, Restart=always) and the
UI owns its configuration by WRITING these two files - launch-shape knobs (assets,
outputs, layer, hwdec, texcomp) live in the env file, and changing one is a service
restart, which is how often they change. Policy stays in the UI; the unit carries
cgroup memory caps (MemoryMax + Restart=always + the engine's own state restore are
the leak backstop).

Pure file generation plus one `systemctl --user daemon-reload`; enabling/disabling
units is models.setMaster's job, never this module's.
"""
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
from pathlib import Path

from .. import constants as C
from ..storage import atomic, lock, paths, settings

ENV_FILE_NAME = "engine-env"
UNIT_FILE_NAME = "lwe-engine.service"

# The real engine binary (NOT the lwe-engine-api shim - the shim dies at cutover).
# settings ENGINE_BIN overrides when it points somewhere other than the shim.
# This is where install.sh puts the engine.
DEFAULT_ENGINE_BIN = os.path.expanduser("~/.local/lib/lwe-engine/linux-wallpaperengine")

_UNIT_TEMPLATE = """\
# lwe-engine.service - LWE wallpaper engine daemon (two-service architecture)
# GENERATED by LWE Control Panel (lwe_ui.engine.daemon_unit) - edit settings, not this.
# MemoryMax + Restart=always + the engine's own state restore are the leak backstop.
[Unit]
Description=LWE wallpaper engine daemon (linux-wallpaperengine --daemon)
PartOf=graphical-session.target
After=graphical-session.target

[Service]
Type=simple
EnvironmentFile=%h/.config/lwe/{env_name}
ExecStart="{engine_bin}" --daemon $LWE_ENGINE_ARGS
Restart=always
RestartSec=5
MemoryHigh=2G
MemoryMax=3G
MemorySwapMax=2G

[Install]
WantedBy=graphical-session.target
"""


def _outputs_hyprctl() -> list[str]:
    exe = shutil.which("hyprctl")
    if not exe:
        return []
    try:
        proc = subprocess.run([exe, "-j", "monitors"], capture_output=True, text=True,
                              timeout=3, check=False)
        return [str(m.get("name") or "") for m in json.loads(proc.stdout or "[]") if m.get("name")]
    except (OSError, subprocess.SubprocessError, ValueError, TypeError):
        return []


def _outputs_kscreen() -> list[str]:
    """KDE Plasma / KWin. `kscreen-doctor -j` reports outputs[] with a name and enabled flag."""
    exe = shutil.which("kscreen-doctor")
    if not exe:
        return []
    try:
        proc = subprocess.run([exe, "-j"], capture_output=True, text=True, timeout=5, check=False)
        data = json.loads(proc.stdout or "{}")
        outs = data.get("outputs") if isinstance(data, dict) else None
        return [str(o.get("name") or "") for o in (outs or [])
                if o.get("name") and o.get("enabled", True)]
    except (OSError, subprocess.SubprocessError, ValueError, TypeError, AttributeError):
        return []


def _outputs_wlr_randr() -> list[str]:
    """Generic wlroots (sway, river, wayfire...). First token of each unindented line."""
    exe = shutil.which("wlr-randr")
    if not exe:
        return []
    try:
        proc = subprocess.run([exe], capture_output=True, text=True, timeout=5, check=False)
        names = []
        for line in (proc.stdout or "").splitlines():
            if line and not line[0].isspace():
                names.append(line.split()[0])
        return names
    except (OSError, subprocess.SubprocessError, IndexError):
        return []


def enumerate_outputs() -> list[str]:
    """Monitor names from the compositor, whichever compositor this is.

    The engine ships cross-compositor, so this must not assume Hyprland: with no names the
    generated env file carries no --screen-root and the daemon boots with nowhere to draw,
    which presents as "installed fine, renders nothing". Tried in order - Hyprland, then
    KDE/KWin, then generic wlroots - and each source is independently tolerant, so an
    absent tool or a changed output format costs nothing but a fall-through.

    Empty means genuinely unresolvable; the caller decides whether that blocks a write.
    """
    for source in (_outputs_hyprctl, _outputs_kscreen, _outputs_wlr_randr):
        try:
            names = [n for n in source() if n]
        except Exception:
            continue   # one broken source must never cost us the rest of the chain
        if names:
            return names
    return []


def resolve_engine_bin() -> str:
    """The engine binary the unit should launch.

    Order: explicit ENGINE_BIN setting, then PATH (where an installed engine
    lives), then the installer's own locations - each only if it actually
    exists, so a generated unit never points at a binary that is not there.
    An empty return means no engine was found; the unit writer refuses.
    """
    binary = str(settings.load().get("ENGINE_BIN") or "").strip()
    if binary and os.path.basename(binary) != "lwe-engine-api" and os.path.isfile(binary):
        return binary
    on_path = shutil.which("linux-wallpaperengine")
    if on_path:
        return on_path
    # menu/autostart launches run before login shells amend PATH, so the
    # installer's target is probed directly, not only through PATH
    installed = os.path.expanduser("~/.local/bin/linux-wallpaperengine")
    if os.path.isfile(installed):
        return installed
    if os.path.isfile(DEFAULT_ENGINE_BIN):
        return DEFAULT_ENGINE_BIN
    return ""


def _fmt_dial(value: float) -> str:
    """Shortest faithful decimal for a dial value (3.0 -> "3", 0.7 -> "0.7").

    The live engine-env carries LWE_AUDIOGAIN=3, not 3.0, and the engine parses either;
    matching the existing form keeps a regenerate a no-op diff when nothing changed.
    """
    text = f"{float(value):.6f}".rstrip("0").rstrip(".")
    return text or "0"


#: The env keys this generator OWNS. Every one but LWE_DEADMAN is resolved from settings on each
#: run, so a hand-edit of one of these is transient by design - the settings store is its source.
#: Anything NOT in this set is a foreign line and is preserved verbatim (see _foreign_lines).
#: LWE_NOPAUSEVRAM is RETIRED (the engine no longer reads it) but stays owned: ownership of
#: a key the generator never emits is what scrubs the stale line from older env files,
#: instead of carrying it forever under the foreign-lines banner.
MANAGED_ENV_KEYS = frozenset({
    "LWE_ENGINE_ARGS", "LWE_HWDEC", "LWE_TEXCOMP", "LWE_DEADMAN", "LWE_NOPAUSEVRAM",
    "LWE_TEXDETAIL", "LWE_SSFACTOR", "LWE_CLAMPCOMPOSITES",
    *tuple(C.AUDIO_DIAL_ENV.values()),
})


_HEADER = "# GENERATED by LWE Control Panel - edit settings, not this file."
_FOREIGN_BANNER = (
    "# Lines below are NOT managed by the Control Panel. They were found in",
    "# this file and carried through untouched; edit or delete them by hand.",
)
#: Comment lines this generator authors itself; never treated as foreign.
_OWN_COMMENTS = frozenset({_HEADER, *_FOREIGN_BANNER})
#: Only keys with these prefixes are carried through from a hand-edited env file: the
#: engine's own instruments and NVIDIA driver toggles. Anything else in the engine's
#: environment (a loader variable, a PATH) is not this file's business and is dropped
#: as drift, which reconcile_env then repairs on the next panel start.
_FOREIGN_PREFIXES = ("LWE_", "__NV_")


def _foreign_lines(existing: str | None, drop: frozenset[str] = frozenset()) -> list[str]:
    """Lines from the current env file whose key this generator does not own. A key in `drop`
    is left out with its comments, as an owned key is.

    THE HAZARD THIS CLOSES. Until the settings rework, `write_files()` had no
    production caller, so the engine-env on this box
    was generated once and hand-edited ever since. Four debug lines live there by hand -
    LWE_SHADERDUMP_MATCH, LWE_IMGPROBE, LWE_LIGHTDUMP, LWE_AUDIOSTATS - and they are
    INSTRUMENTS, not settings: Developer owns them, no schema key describes them, and no UI
    can put them back. The moment an Advanced row wired a regenerate, a generator that
    emitted only its own lines would have deleted all four, silently, mid-probe.

    So the generator no longer assumes it is the only author of this file. It rewrites the
    keys it owns and carries everything else through untouched. Comments and blank lines
    ride along with the foreign block, because a hand-added line's comment is part of it.
    """
    if not existing:
        return []
    kept: list[str] = []
    pending: list[str] = []          # comments/blanks buffered until we know what follows
    for raw in existing.splitlines():
        line = raw.rstrip("\n")
        stripped = line.strip()
        # the generator's OWN banner must not be re-collected as foreign, or every
        # regenerate would stack another copy of it above the preserved block
        if stripped in _OWN_COMMENTS:
            continue
        if not stripped or stripped.startswith("#"):
            pending.append(line)
            continue
        key = stripped.split("=", 1)[0].strip()
        if key in MANAGED_ENV_KEYS or key in drop or not key.startswith(_FOREIGN_PREFIXES):
            pending.clear()          # re-emitted by the generator, or not this file's to keep
            continue
        kept.extend(pending)
        pending.clear()
        kept.append(line)
    # the separator blank line this generator writes above the banner would otherwise be
    # re-collected on the next pass and pushed one line further down each time
    while kept and not kept[0].strip():
        kept.pop(0)
    return kept


_LINE_BREAKS = "\n\r\x0b\x0c\x1c\x1d\x1e\x85\u2028\u2029"
_LINE_KEY_RE = re.compile(r"(?:LWE_|__NV_)[A-Za-z0-9_]*\Z")
_DEADMAN_RE = re.compile(r"[ \t\n\v\f\r]*[+-]?[0-9]+")


def _env_value(value: str) -> str:
    """`value` as an engine-env line writes it: bare unless it holds a space, quote, backslash,
    $ or backtick; then single-quoted, or double-quoted with \\" \\\\ \\` \\$ escaped when it holds a
    single quote. NUL, or any character the file is read back as ending a line at (read_text
    and str.splitlines, _LINE_BREAKS), raises ValueError."""
    if "\0" in value or any(c in value for c in _LINE_BREAKS):
        raise ValueError(f"an engine-env value cannot hold a line break or NUL: {value!r}")
    if not any(c in value for c in " \"'\\$`"):
        return value
    # systemd's EnvironmentFile reads '...' verbatim and undoes only \" \\ \` \$ inside "..."
    if "'" not in value:
        return f"'{value}'"
    return '"' + re.sub(r'([\\"`$])', r"\\\1", value) + '"'


def _deadman_ok(value: str | None) -> bool:
    """True for a watchdog value the engine takes: strtol's leading integer, 0 to 86400
    seconds (Config.cpp)."""
    m = _DEADMAN_RE.match(value or "")
    return m is not None and 0 <= int(m.group(0)) <= 86400


def _line_key(line: str) -> str:
    """The variable an env line assigns; "" for a comment, a blank or a line without =."""
    stripped = line.strip()
    if stripped.startswith("#") or "=" not in stripped:
        return ""
    return stripped.split("=", 1)[0].strip()


def build_env_content(outputs: list[str] | None = None, existing: str | None = None,
                      edits: dict[str, str | None] | None = None) -> str:
    """The engine daemon's launch-shape env, resolved from settings.
    Everything per-wallpaper rides `show` instead; everything
    session-global has a verb; only true launch shape lands here.

    `existing` is the current file's text; any line whose key this generator does not own is
    preserved (see _foreign_lines). Passing None means "no file yet", not "discard".
    LWE_DEADMAN keeps the file's value when the engine takes it (_deadman_ok), else 300.
    `edits` ({VAR: value, or None}, checked by write_env) sets or removes lines the generator
    does not own, and sets LWE_DEADMAN's kept value, None restoring 300.
    """
    edits = edits or {}
    s = settings.load()
    outs = outputs if outputs is not None else enumerate_outputs()

    args: list[str] = []
    assets = str(s.get("ASSETS_DIR") or "").strip()
    if assets:
        # systemd word-splits $LWE_ENGINE_ARGS with no quote processing, so a value
        # these characters appear in cannot be represented in the env file at all -
        # refuse loudly instead of writing a unit that silently mis-parses.
        if any(c in assets for c in ' \t"\n'):
            raise ValueError(
                f"ASSETS_DIR {assets!r} contains whitespace or quotes; "
                "the engine service cannot represent it - move the assets to a "
                "plain path or leave ASSETS_DIR empty for auto-discovery")
        args += ["--assets-dir", assets]
    for name in outs:
        # the same word-splitting hazard as ASSETS_DIR above; a name like that is not an
        # output this file can name, so it is left out rather than written broken
        if any(c in name for c in ' \t"\n'):
            continue
        args += ["--screen-root", name]
    layer = str(s.get("ENGINE_LAYER") or "bottom").strip()
    if layer and layer != "bottom":
        args += ["--layer", layer]

    texcomp = "1" if str(s.get("ENGINE_TEXCOMP", True)).lower() in ("1", "true", "yes", "on") else "0"
    deadman = (edits["LWE_DEADMAN"] if "LWE_DEADMAN" in edits
               else parse_env((existing or "").splitlines()).get("LWE_DEADMAN"))
    lines = [
        _HEADER,
        "LWE_ENGINE_ARGS=" + " ".join(args),
        f"LWE_HWDEC={s.get('ENGINE_HWDEC') or 'no'}",
        # value-inspected by the engine ("1" vs "0"), so writing "0" really does disable it
        f"LWE_TEXCOMP={texcomp}",
        f"LWE_DEADMAN={_env_value(deadman) if _deadman_ok(deadman) else '300'}",
    ]

    # written either way: the engine caps by default, so "full" must say so explicitly
    detail = str(s.get("TEXTURE_DETAIL") or "auto").strip()
    lines.append(f"LWE_TEXDETAIL={detail if detail in C.TEXTURE_DETAILS else 'auto'}")

    # the engine clamps everything by default; sharpfx turns the effect clamp off and wallpaper turns both off
    res = str(s.get("RENDER_RESOLUTION") or "screen").strip()
    if res == "sharpfx":
        lines.append("LWE_CLAMPCOMPOSITES=0")
    elif res == "wallpaper":
        lines.append("LWE_SSFACTOR=0")
        lines.append("LWE_CLAMPCOMPOSITES=0")

    for skey, env_name in C.AUDIO_DIAL_ENV.items():
        try:
            value = float(s.get(skey, C.SETTINGS_SCHEMA[skey]["default"]))
        except (TypeError, ValueError):
            value = float(C.SETTINGS_SCHEMA[skey]["default"])
        lines.append(f"{env_name}={_fmt_dial(value)}")

    foreign = _foreign_lines(existing, frozenset(k for k, v in edits.items() if v is None))
    for key, value in edits.items():
        if value is None or key == "LWE_DEADMAN":
            continue
        line = f"{key}={_env_value(value)}"
        at = [i for i, kept in enumerate(foreign) if _line_key(kept) == key]
        if at:
            foreign[at[-1]] = line
        else:
            foreign.append(line)
    if foreign:
        lines.append("")
        lines.extend(_FOREIGN_BANNER)
        lines.extend(foreign)

    return "\n".join(lines) + "\n"


def write_env(lines: dict[str, object] | None = None, outputs: list[str] | None = None) -> str:
    """Rebuild engine-env alone through the one generator; return "written", "unchanged" or
    "no screens". `lines` ({VAR: value, or None to remove}) edits the lines the generator does
    not own, and LWE_DEADMAN sets its kept value (None restores 300); another owned key, or a
    name engine-env does not carry (LWE_ and __NV_ names only), raises ValueError. With no
    outputs (given, else enumerated) the file is left exactly as it was, the lines named in
    `lines` included. Never the unit, never systemctl."""
    edits = {key: None if value is None else str(value) for key, value in (lines or {}).items()}
    for key, value in edits.items():
        if key != "LWE_DEADMAN" and key in MANAGED_ENV_KEYS:
            raise ValueError(f"{key} belongs to the engine-env generator and cannot be set as a line")
        if not _LINE_KEY_RE.match(key):
            raise ValueError(f"{key!r} is not a name engine-env keeps (LWE_ or __NV_ names only)")
        if value is not None:
            _env_value(value)
    outs = enumerate_outputs() if outputs is None else list(outputs)
    if not outs:
        return "no screens"
    env_path = paths.config_dir() / ENV_FILE_NAME
    with lock.held("env"):
        try:
            existing = env_path.read_text(encoding="utf-8")
        except OSError:
            existing = None
        text = build_env_content(outs, existing, edits)
        if text == existing:
            return "unchanged"
        atomic.atomic_write_text(env_path, text)
    return "written"


def reconcile_env() -> bool:
    """Panel-startup drift repair: env regeneration must never
    need a manual trigger. The env file only used to change on explicit commits of
    regenerate-class keys, so a panel upgrade that adds a managed key - Texture detail
    was the one that surfaced this - left the file stale forever with nothing a user
    could do about it short of editing settings they had no reason to touch.

    On every panel start: compute what settings truth would generate and rewrite the
    file on any drift (foreign lines still preserved). The engine reads the file only
    at service start, so this is a quiet file repair - the running engine is never
    touched, and the change lands at whatever restart happens next.

    Skipped entirely when outputs cannot be enumerated - a reconcile must never
    degrade the file to an engine with nowhere to draw. It writes engine-env only, through
    write_env; the unit and daemon-reload belong to write_files."""
    try:
        settings.load()
    except Exception:
        return False
    return write_env(outputs=enumerate_outputs()) == "written"


def write_files(outputs: list[str] | None = None) -> tuple[str, str]:
    """The service operations' writer: engine-env through write_env (left as it was when no
    output is found), then the unit only when its text changed, then daemon-reload; return
    their paths. A failed daemon-reload raises naming `systemctl --user daemon-reload`. Never
    enables."""
    env_path = paths.config_dir() / ENV_FILE_NAME
    with lock.held("env"):
        write_env(outputs=outputs)

        unit_dir = os.path.expanduser("~/.config/systemd/user")
        os.makedirs(unit_dir, exist_ok=True)
        unit_path = os.path.join(unit_dir, UNIT_FILE_NAME)
        engine_bin = resolve_engine_bin()
        if not engine_bin:
            raise ValueError(
                "no engine binary found: install linux-wallpaperengine on PATH "
                "or set ENGINE_BIN in settings")
        if '"' in engine_bin or "\n" in engine_bin:
            raise ValueError(f"engine path {engine_bin!r} cannot be written into a unit file")
        # quoted ExecStart handles spaces; % is a systemd specifier and must be doubled
        unit_text = _UNIT_TEMPLATE.format(env_name=ENV_FILE_NAME,
                                          engine_bin=engine_bin.replace("%", "%%"))
        try:
            unit_same = Path(unit_path).read_text(encoding="utf-8") == unit_text
        except OSError:
            unit_same = False
        if not unit_same:
            atomic.atomic_write_text(unit_path, unit_text)

    try:
        reload_proc = subprocess.run(["systemctl", "--user", "daemon-reload"],
                                     capture_output=True, text=True, timeout=10, check=False)
    except (OSError, subprocess.SubprocessError) as exc:
        raise RuntimeError(
            f"systemd daemon-reload failed: {exc}; run systemctl --user daemon-reload") from exc
    if reload_proc.returncode != 0:
        raise RuntimeError(
            "systemd daemon-reload failed: "
            + (reload_proc.stderr.strip() or f"exit {reload_proc.returncode}")
            + "; run systemctl --user daemon-reload")
    return str(env_path), unit_path


#: env keys per restart-class setting; a (key, flag) probe is one token of a
#: word-split argument line. Only these are compared; a drop-in or environment.d
#: value for one of them is not seen.
RESTART_ENV_KEYS: dict[str, tuple[str | tuple[str, str], ...]] = {
    "ENGINE_LAYER": (("LWE_ENGINE_ARGS", "--layer"),),
    "ENGINE_HWDEC": ("LWE_HWDEC",),
    "TEXTURE_DETAIL": ("LWE_TEXDETAIL",),
    "RENDER_RESOLUTION": ("LWE_SSFACTOR", "LWE_CLAMPCOMPOSITES"),
    "ENGINE_TEXCOMP": ("LWE_TEXCOMP",),
}


def _probe(env: dict[str, str], probe: str | tuple[str, str]) -> str | None:
    """One probe's value in an environment: the key's value, or the token after `flag`
    in the key's value split on whitespace, which is how systemd splits the line."""
    if isinstance(probe, tuple):
        key, flag = probe
        words = env.get(key, "").split()
        for i, word in enumerate(words[:-1]):
            if word == flag:
                return words[i + 1]
        return None
    return env.get(probe)


def parse_env(lines) -> dict[str, str]:
    """KEY=VALUE entries to a dict; comments, blanks and lines without = are skipped. A value
    in double quotes also loses its \\" \\\\ \\` \\$ escapes."""
    out: dict[str, str] = {}
    for line in lines:
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        value = value.strip()
        # systemd strips one pair of matching quotes from an EnvironmentFile value
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1] if value[0] == "'" else re.sub(r'\\([\\"`$])', r"\1", value[1:-1])
        out[key.strip()] = value
    return out


def live_engine_env() -> dict[str, str] | None:
    """The environment the running engine started with, read from its own process.

    systemd hands the env file to the process at start and the unit reports none of it
    back, so the process is the only record of what the engine actually read. None when
    the service has no main process, when it cannot be read, or while the main process
    is forked but has not exec'd the engine yet: a simple unit's start job completes at
    the fork, and until the exec its environment is still the manager's own.
    """
    if os.environ.get("LWE_SANDBOX") == "1":
        return None
    try:
        proc = subprocess.run(
            ["systemctl", "--user", "show", C.ENGINE_SERVICE, "-p", "MainPID", "--value"],
            capture_output=True, text=True, timeout=3, check=False)
    except (OSError, subprocess.SubprocessError):
        return None
    pid = (proc.stdout or "").strip()
    if proc.returncode != 0 or not pid.isdigit() or pid == "0":
        return None
    try:
        raw = Path(f"/proc/{pid}/environ").read_bytes()
    except OSError:
        return None
    env = parse_env(chunk.decode("utf-8", "replace") for chunk in raw.split(b"\0"))
    if "LWE_ENGINE_ARGS" not in env:
        return None
    return env


def _read_env_file() -> dict[str, str] | None:
    try:
        text = (paths.config_dir() / ENV_FILE_NAME).read_text(encoding="utf-8")
    except OSError:
        return None
    return parse_env(text.splitlines())


def restart_state(live: dict[str, str] | None = None,
                  env_text: str | None = None) -> tuple[bool, dict[str, bool]]:
    """(observed, pending). observed is False while the engine process or the env file
    cannot be read, and pending is then all False: no running engine means nothing is
    pending, the next start reads the file. Otherwise pending maps every restart-class
    setting to True when the running engine started with other values than the file now
    carries for the keys that setting owns. One read of the process and one of the file
    answer all of them. `live` and `env_text` are injectable for tests.

    The file is read from the panel's config dir; the unit names it under the home
    directory, so a config home pointed elsewhere compares against a file the engine never
    reads. Keys the writer always emits (LWE_HWDEC, LWE_TEXDETAIL) pend against an engine
    started before the line existed; that engine did not read the setting.
    """
    if live is None:
        live = live_engine_env()
    if live is None:
        return False, {k: False for k in RESTART_ENV_KEYS}
    wanted = parse_env(env_text.splitlines()) if env_text is not None else _read_env_file()
    if wanted is None:
        return False, {k: False for k in RESTART_ENV_KEYS}
    return True, {k: any(_probe(wanted, probe) != _probe(live, probe) for probe in probes)
                  for k, probes in RESTART_ENV_KEYS.items()}


def restart_pending_keys(live: dict[str, str] | None = None,
                         env_text: str | None = None) -> dict[str, bool]:
    """The pending map of `restart_state`."""
    return restart_state(live, env_text)[1]


def restart_pending(setting_key: str, live: dict[str, str] | None = None,
                    env_text: str | None = None) -> bool:
    """One setting's answer from `restart_pending_keys`; a key with no env keys never pends."""
    return restart_pending_keys(live, env_text).get(setting_key, False)
