"""Writer for the lwe-engine.service unit + its environment file.

The two-service architecture's mechanism half: the engine becomes a first-class
systemd user daemon (`--daemon` idle boot, socket control, Restart=always) and the
UI owns its configuration by WRITING these two files - launch-shape knobs (assets,
outputs, layer, hwdec, texcomp) live in the env file, and changing one is a service
restart, which is how often they change. Policy stays in the UI; the unit carries
cgroup memory caps (MemoryMax + Restart=always + the engine's own state restore are
the leak backstop).

Pure file generation plus one `systemctl --user daemon-reload`; enabling/disabling
units is models.setMaster's job, never this module's.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess

from .. import constants as C
from ..storage import atomic, paths, settings

ENV_FILE_NAME = "engine-env"
UNIT_FILE_NAME = "lwe-engine.service"

# The real engine binary (NOT the lwe-engine-api shim - the shim dies at cutover).
# settings ENGINE_BIN overrides when it points somewhere other than the shim.
DEFAULT_ENGINE_BIN = os.path.expanduser("~/src/linux-wallpaperengine/build/output/linux-wallpaperengine")

_UNIT_TEMPLATE = """\
# lwe-engine.service - LWE wallpaper engine daemon (two-service architecture)
# GENERATED by LWE Control Panel (lwe_ui.engine.daemon_unit) - edit settings, not this.
# MemoryMax + Restart=always + the engine's own state restore are the leak backstop.
[Unit]
Description=LWE wallpaper engine daemon (linux-wallpaperengine --daemon)
PartOf=graphical-session.target
After=graphical-session.target

[Service]
Type=simple
EnvironmentFile=%h/.config/lwe/{env_name}
ExecStart="{engine_bin}" --daemon $LWE_ENGINE_ARGS
Restart=always
RestartSec=5
MemoryHigh=2G
MemoryMax=3G
MemorySwapMax=2G

[Install]
WantedBy=graphical-session.target
"""


def _outputs_hyprctl() -> list[str]:
    exe = shutil.which("hyprctl")
    if not exe:
        return []
    try:
        proc = subprocess.run([exe, "-j", "monitors"], capture_output=True, text=True,
                              timeout=3, check=False)
        return [str(m.get("name") or "") for m in json.loads(proc.stdout or "[]") if m.get("name")]
    except (OSError, subprocess.SubprocessError, ValueError, TypeError):
        return []


def _outputs_kscreen() -> list[str]:
    """KDE Plasma / KWin. `kscreen-doctor -j` reports outputs[] with a name and enabled flag."""
    exe = shutil.which("kscreen-doctor")
    if not exe:
        return []
    try:
        proc = subprocess.run([exe, "-j"], capture_output=True, text=True, timeout=5, check=False)
        data = json.loads(proc.stdout or "{}")
        outs = data.get("outputs") if isinstance(data, dict) else None
        return [str(o.get("name") or "") for o in (outs or [])
                if o.get("name") and o.get("enabled", True)]
    except (OSError, subprocess.SubprocessError, ValueError, TypeError, AttributeError):
        return []


def _outputs_wlr_randr() -> list[str]:
    """Generic wlroots (sway, river, wayfire...). First token of each unindented line."""
    exe = shutil.which("wlr-randr")
    if not exe:
        return []
    try:
        proc = subprocess.run([exe], capture_output=True, text=True, timeout=5, check=False)
        names = []
        for line in (proc.stdout or "").splitlines():
            if line and not line[0].isspace():
                names.append(line.split()[0])
        return names
    except (OSError, subprocess.SubprocessError, IndexError):
        return []


def enumerate_outputs() -> list[str]:
    """Monitor names from the compositor, whichever compositor this is.

    The engine ships cross-compositor, so this must not assume Hyprland: with no names the
    generated env file carries no --screen-root and the daemon boots with nowhere to draw,
    which presents as "installed fine, renders nothing". Tried in order - Hyprland, then
    KDE/KWin, then generic wlroots - and each source is independently tolerant, so an
    absent tool or a changed output format costs nothing but a fall-through.

    Empty means genuinely unresolvable; the caller decides whether that blocks a write.
    """
    for source in (_outputs_hyprctl, _outputs_kscreen, _outputs_wlr_randr):
        try:
            names = [n for n in source() if n]
        except Exception:
            continue   # one broken source must never cost us the rest of the chain
        if names:
            return names
    return []


def resolve_engine_bin() -> str:
    """The engine binary the unit should launch.

    Order: explicit ENGINE_BIN setting, then PATH (where an installed engine
    lives), then the source-checkout build path - each only if it actually
    exists, so a generated unit never points at a binary that is not there.
    An empty return means no engine was found; the unit writer refuses.
    """
    binary = str(settings.load().get("ENGINE_BIN") or "").strip()
    if binary and os.path.basename(binary) != "lwe-engine-api" and os.path.isfile(binary):
        return binary
    on_path = shutil.which("linux-wallpaperengine")
    if on_path:
        return on_path
    # menu/autostart launches run before login shells amend PATH, so the
    # installer's target is probed directly, not only through PATH
    installed = os.path.expanduser("~/.local/bin/linux-wallpaperengine")
    if os.path.isfile(installed):
        return installed
    if os.path.isfile(DEFAULT_ENGINE_BIN):
        return DEFAULT_ENGINE_BIN
    return ""


def _fmt_dial(value: float) -> str:
    """Shortest faithful decimal for a dial value (3.0 -> "3", 0.7 -> "0.7").

    The live engine-env carries LWE_AUDIOGAIN=3, not 3.0, and the engine parses either;
    matching the existing form keeps a regenerate a no-op diff when nothing changed.
    """
    text = f"{float(value):.6f}".rstrip("0").rstrip(".")
    return text or "0"


#: The env keys this generator OWNS. Every one is resolved from settings on each run, so a
#: hand-edit of one of these is transient by design - the settings store is its source.
#: Anything NOT in this set is a foreign line and is preserved verbatim (see _foreign_lines).
#: LWE_NOPAUSEVRAM is RETIRED (the engine no longer reads it) but stays owned: ownership of
#: a key the generator never emits is what scrubs the stale line from older env files,
#: instead of carrying it forever under the foreign-lines banner.
MANAGED_ENV_KEYS = frozenset({
    "LWE_ENGINE_ARGS", "LWE_HWDEC", "LWE_TEXCOMP", "LWE_DEADMAN", "LWE_NOPAUSEVRAM",
    "LWE_TEXDETAIL", "LWE_TEXCAP",
    *tuple(C.AUDIO_DIAL_ENV.values()),
})


_HEADER = "# GENERATED by LWE Control Panel - edit settings, not this file."
_FOREIGN_BANNER = (
    "# Lines below are NOT managed by the Control Panel. They were found in",
    "# this file and carried through untouched; edit or delete them by hand.",
)
#: Comment lines this generator authors itself; never treated as foreign.
_OWN_COMMENTS = frozenset({_HEADER, *_FOREIGN_BANNER})


def _foreign_lines(existing: str | None) -> list[str]:
    """Lines from the current env file whose key this generator does not own.

    THE HAZARD THIS CLOSES. Until the settings rework, `write_files()` had no
    production caller, so the engine-env on this box
    was generated once and hand-edited ever since. Four debug lines live there by hand -
    LWE_SHADERDUMP_MATCH, LWE_IMGPROBE, LWE_LIGHTDUMP, LWE_AUDIOSTATS - and they are
    INSTRUMENTS, not settings: Developer owns them, no schema key describes them, and no UI
    can put them back. The moment an Advanced row wired a regenerate, a generator that
    emitted only its own lines would have deleted all four, silently, mid-probe.

    So the generator no longer assumes it is the only author of this file. It rewrites the
    keys it owns and carries everything else through untouched. Comments and blank lines
    ride along with the foreign block, because a hand-added line's comment is part of it.
    """
    if not existing:
        return []
    kept: list[str] = []
    pending: list[str] = []          # comments/blanks buffered until we know what follows
    for raw in existing.splitlines():
        line = raw.rstrip("\n")
        stripped = line.strip()
        # the generator's OWN banner must not be re-collected as foreign, or every
        # regenerate would stack another copy of it above the preserved block
        if stripped in _OWN_COMMENTS:
            continue
        if not stripped or stripped.startswith("#"):
            pending.append(line)
            continue
        key = stripped.split("=", 1)[0].strip()
        if key in MANAGED_ENV_KEYS:
            pending.clear()          # the generator re-emits this line and its own comment
            continue
        kept.extend(pending)
        pending.clear()
        kept.append(line)
    # the separator blank line this generator writes above the banner would otherwise be
    # re-collected on the next pass and pushed one line further down each time
    while kept and not kept[0].strip():
        kept.pop(0)
    return kept


def build_env_content(outputs: list[str] | None = None, existing: str | None = None) -> str:
    """The engine daemon's launch-shape env, resolved from settings.
    Everything per-wallpaper rides `show` instead; everything
    session-global has a verb; only true launch shape lands here.

    `existing` is the current file's text; any line whose key this generator does not own is
    preserved (see _foreign_lines). Passing None means "no file yet", not "discard".
    """
    s = settings.load()
    outs = outputs if outputs is not None else enumerate_outputs()

    args: list[str] = []
    assets = str(s.get("ASSETS_DIR") or "").strip()
    if assets:
        # systemd word-splits $LWE_ENGINE_ARGS with no quote processing, so a value
        # these characters appear in cannot be represented in the env file at all -
        # refuse loudly instead of writing a unit that silently mis-parses.
        if any(c in assets for c in ' \t"\n'):
            raise ValueError(
                f"ASSETS_DIR {assets!r} contains whitespace or quotes; "
                "the engine service cannot represent it - move the assets to a "
                "plain path or leave ASSETS_DIR empty for auto-discovery")
        args += ["--assets-dir", assets]
    for name in outs:
        args += ["--screen-root", name]
    layer = str(s.get("ENGINE_LAYER") or "bottom").strip()
    if layer and layer != "bottom":
        args += ["--layer", layer]

    texcomp = "1" if str(s.get("ENGINE_TEXCOMP", True)).lower() in ("1", "true", "yes", "on") else "0"
    lines = [
        _HEADER,
        "LWE_ENGINE_ARGS=" + " ".join(args),
        f"LWE_HWDEC={s.get('ENGINE_HWDEC') or 'no'}",
        # value-inspected by the engine ("1" vs "0"), so writing "0" really does disable it
        f"LWE_TEXCOMP={texcomp}",
        "LWE_DEADMAN=300",
    ]

    # written either way: the engine caps by default, so "full" must say so explicitly
    detail = str(s.get("TEXTURE_DETAIL") or "auto").strip()
    lines.append(f"LWE_TEXDETAIL={detail if detail in C.TEXTURE_DETAILS else 'auto'}")

    for skey, env_name in C.AUDIO_DIAL_ENV.items():
        try:
            value = float(s.get(skey, C.SETTINGS_SCHEMA[skey]["default"]))
        except (TypeError, ValueError):
            value = float(C.SETTINGS_SCHEMA[skey]["default"])
        lines.append(f"{env_name}={_fmt_dial(value)}")

    foreign = _foreign_lines(existing)
    if foreign:
        lines.append("")
        lines.extend(_FOREIGN_BANNER)
        lines.extend(foreign)

    return "\n".join(lines) + "\n"


def reconcile_env() -> bool:
    """Panel-startup drift repair: env regeneration must never
    need a manual trigger. The env file only used to change on explicit commits of
    regenerate-class keys, so a panel upgrade that adds a managed key - Texture detail
    was the one that surfaced this - left the file stale forever with nothing a user
    could do about it short of editing settings they had no reason to touch.

    On every panel start: compute what settings truth would generate and rewrite the
    file on any drift (foreign lines still preserved). The engine reads the file only
    at service start, so this is a quiet file repair - the running engine is never
    touched, and the change lands at whatever restart happens next.

    Skipped entirely when outputs cannot be enumerated - a reconcile must never
    degrade the file to an engine with nowhere to draw."""
    try:
        settings.load()
    except Exception:
        return False
    outs = enumerate_outputs()
    if not outs:
        return False
    env_path = paths.config_dir() / ENV_FILE_NAME
    try:
        existing = env_path.read_text(encoding="utf-8")
    except OSError:
        existing = None
    if existing is not None and existing == build_env_content(outs, existing):
        return False
    write_files(outs)
    return True


def write_files(outputs: list[str] | None = None) -> tuple[str, str]:
    """Write env file + unit file, daemon-reload, return their paths. Never enables."""
    env_path = paths.config_dir() / ENV_FILE_NAME
    try:
        existing = env_path.read_text(encoding="utf-8")
    except OSError:
        existing = None
    atomic.atomic_write_text(env_path, build_env_content(outputs, existing))

    unit_dir = os.path.expanduser("~/.config/systemd/user")
    os.makedirs(unit_dir, exist_ok=True)
    unit_path = os.path.join(unit_dir, UNIT_FILE_NAME)
    engine_bin = resolve_engine_bin()
    if not engine_bin:
        raise ValueError(
            "no engine binary found: install linux-wallpaperengine on PATH "
            "or set ENGINE_BIN in settings")
    if '"' in engine_bin or "\n" in engine_bin:
        raise ValueError(f"engine path {engine_bin!r} cannot be written into a unit file")
    # quoted ExecStart handles spaces; % is a systemd specifier and must be doubled
    atomic.atomic_write_text(unit_path, _UNIT_TEMPLATE.format(
        env_name=ENV_FILE_NAME, engine_bin=engine_bin.replace("%", "%%")))

    try:
        reload_proc = subprocess.run(["systemctl", "--user", "daemon-reload"],
                                     capture_output=True, text=True, timeout=10, check=False)
    except (OSError, subprocess.SubprocessError) as exc:
        raise RuntimeError(f"systemd daemon-reload failed: {exc}") from exc
    if reload_proc.returncode != 0:
        raise RuntimeError(
            "systemd daemon-reload failed: "
            + (reload_proc.stderr.strip() or f"exit {reload_proc.returncode}"))
    return str(env_path), unit_path
