"""The two clamp numbers are saved settings, SSFACTOR and CLAMPCOMPOSITES, in settings.conf and in
each wallpaper's file; an absent key reads the file's RENDER_RESOLUTION word per number.

settings.load and the settings restore map the word for a key the file or the archive lacks; a
whole-file save materializes the same numbers and keeps the word; the env file is byte-identical
for every old word and writes a number only when it differs from 1; the show resolver sends each
number a wallpaper decides, own or from its word, clamped, never a non-finite one; the wallpaper
store keeps presence raw, so a revert restores absence; an unset writes the `KEY=` marker or a 1
only where the word would otherwise decide; the clean-up keeps the markers; the push rows treat
the pair as restart settings and wallpaper build keys.

Run: PYTHONPATH=src python3 tests/test_clamp_keys.py
"""
import _sandbox  # noqa: F401  (pins the engine socket before any lwe_ui import)
import json
import os
import shutil
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

SRC = Path(__file__).resolve().parent.parent / "src"
sys.path.insert(0, str(SRC))
FIXTURES = Path(__file__).resolve().parent / "fixtures" / "backups"

_BOOT = tempfile.TemporaryDirectory(prefix="lwe-clamp-boot-")
for _key, _sub in (("HOME", ""), ("XDG_CONFIG_HOME", "c"), ("XDG_STATE_HOME", "s"), ("XDG_DATA_HOME", "d"),
                   ("XDG_CACHE_HOME", "k")):
    os.environ[_key] = os.path.join(_BOOT.name, _sub) if _sub else _BOOT.name

from lwe_ui import constants as C  # noqa: E402
from lwe_ui.engine import daemon_unit, marker, push, resolve  # noqa: E402
from lwe_ui.storage import backup, migrate, paths, playlists, settings, wp  # noqa: E402

GOLDEN = {
    "screen": ("# GENERATED by LWE Control Panel - edit settings, not this file.\n"
               "LWE_ENGINE_ARGS=--screen-root DP-1\nLWE_HWDEC=no\nLWE_TEXCOMP=1\nLWE_DEADMAN=300\n"
               "LWE_TEXDETAIL=auto\nLWE_AUDIOGAIN=3\nLWE_CLASSICK=0.7\nLWE_CLASSICEXP=2.6\n"),
    "sharpfx": ("# GENERATED by LWE Control Panel - edit settings, not this file.\n"
                "LWE_ENGINE_ARGS=--screen-root DP-1\nLWE_HWDEC=no\nLWE_TEXCOMP=1\nLWE_DEADMAN=300\n"
                "LWE_TEXDETAIL=auto\nLWE_CLAMPCOMPOSITES=0\nLWE_AUDIOGAIN=3\nLWE_CLASSICK=0.7\n"
                "LWE_CLASSICEXP=2.6\n"),
    "wallpaper": ("# GENERATED by LWE Control Panel - edit settings, not this file.\n"
                  "LWE_ENGINE_ARGS=--screen-root DP-1\nLWE_HWDEC=no\nLWE_TEXCOMP=1\nLWE_DEADMAN=300\n"
                  "LWE_TEXDETAIL=auto\nLWE_SSFACTOR=0\nLWE_CLAMPCOMPOSITES=0\nLWE_AUDIOGAIN=3\n"
                  "LWE_CLASSICK=0.7\nLWE_CLASSICEXP=2.6\n"),
}


class ClampKeysTest(unittest.TestCase):
    def setUp(self) -> None:
        self.home = Path(tempfile.mkdtemp(prefix="lwe-clamp-"))
        self.addCleanup(shutil.rmtree, self.home, True)
        for key, sub in (("HOME", ""), ("XDG_CONFIG_HOME", "c"), ("XDG_STATE_HOME", "s"),
                         ("XDG_DATA_HOME", "d"), ("XDG_CACHE_HOME", "k")):
            os.environ[key] = str(self.home / sub) if sub else str(self.home)
        paths.ensure_dirs()
        self.runs: list = []
        for name, value in (("enumerate_outputs", lambda: ["DP-1"]),
                            ("subprocess", mock.Mock(run=lambda *a, **k: self.runs.append(a)))):
            patcher = mock.patch.object(daemon_unit, name, value)
            patcher.start()
            self.addCleanup(patcher.stop)

    def _settings(self, text: str) -> None:
        paths.settings_file().write_text(text, encoding="utf-8")

    def _clamps(self) -> tuple:
        s = settings.load()
        return s["SSFACTOR"], s["CLAMPCOMPOSITES"]

    def _text(self, path: Path) -> str:
        return path.read_text(encoding="utf-8")

    def test_an_absent_clamp_key_reads_the_file_s_word(self) -> None:
        for body, want in (("RENDER_RESOLUTION=screen\n", (1.0, 1.0)), ("RENDER_RESOLUTION=sharpfx\n", (1.0, 0.0)),
                           ("RENDER_RESOLUTION=wallpaper\n", (0.0, 0.0)), ("", (1.0, 1.0)),
                           ("RENDER_RESOLUTION=bogus\n", (1.0, 1.0))):
            with self.subTest(body=body):
                self._settings(body)
                self.assertEqual(self._clamps(), want)

    def test_setting_one_number_on_a_sharpfx_file_leaves_the_other_derived(self) -> None:
        self._settings("RENDER_RESOLUTION=sharpfx\n")
        settings.update({"SSFACTOR": 2})
        env = daemon_unit.build_env_content(outputs=["DP-1"])
        self.assertIn("LWE_SSFACTOR=2\n", env)
        self.assertIn("LWE_CLAMPCOMPOSITES=0\n", env)

    def test_a_whole_file_save_materializes_the_numbers_and_keeps_the_word(self) -> None:
        self._settings("RENDER_RESOLUTION=sharpfx\n")
        settings.save(settings.load())
        text = self._text(paths.settings_file())
        for line in ("RENDER_RESOLUTION=sharpfx\n", "SSFACTOR=1.0\n", "CLAMPCOMPOSITES=0.0\n"):
            self.assertIn(line, text)
        self.assertEqual(self._clamps(), (1.0, 0.0))

    def test_an_old_archive_restores_its_word_over_the_current_numbers(self) -> None:
        archive = FIXTURES / "corpus-6255bb5719-1.lwebackup"
        record = json.loads(archive.with_suffix(".json").read_text(encoding="utf-8"))
        self.assertEqual(record["settings"]["RENDER_RESOLUTION"], "sharpfx")
        self.assertNotIn("SSFACTOR", record["settings"])
        lib = self.home / "wallpapers"
        for wid in record["library_present"]:
            (lib / wid).mkdir(parents=True)
        settings.ensure_exists()
        settings.update({"WALLPAPERS_DIR": str(lib), "SSFACTOR": 1.0, "CLAMPCOMPOSITES": 1.0})
        r = backup.apply(backup.preflight(str(archive)))
        self.assertEqual(r["errors"], [])
        self.assertEqual(self._clamps(), (1.0, 0.0))

    def test_the_env_file_is_byte_identical_for_each_word(self) -> None:
        for word, text in GOLDEN.items():
            with self.subTest(word=word):
                settings.save({"RENDER_RESOLUTION": word, "ASSETS_DIR": ""})
                self.assertEqual(daemon_unit.build_env_content(outputs=["DP-1"]), text)

    def test_the_env_file_writes_a_number_only_when_it_differs_from_1(self) -> None:
        for key in C.CLAMP_KEYS:
            for value, line in (("1.5", "1.5"), ("1", None), ("0", "0"), ("5", "4"), ("nan", None)):
                with self.subTest(key=key, value=value):
                    self._settings(f"RENDER_RESOLUTION=screen\n{key}={value}\n")
                    env = daemon_unit.build_env_content(outputs=["DP-1"])
                    if line is None:
                        self.assertNotIn(f"LWE_{key}=", env)
                    else:
                        self.assertIn(f"LWE_{key}={line}\n", env)

    def test_the_resolver_sends_each_number_a_wallpaper_decides(self) -> None:
        for wid, body, want in (
                ("301", "SSFACTOR=2\n", {"ssfactor": 2.0}),
                ("302", "RENDER_RESOLUTION=sharpfx\n", {"ssfactor": 1.0, "clampcomposites": 0.0}),
                ("303", "RENDER_RESOLUTION=wallpaper\nSSFACTOR=2\n", {"ssfactor": 2.0, "clampcomposites": 0.0}),
                ("304", "RENDER_RESOLUTION=sharpfx\nSSFACTOR=\n", {"clampcomposites": 0.0}),
                ("305", "SSFACTOR=7\n", {"ssfactor": 4.0}),
                ("306", "SSFACTOR=nan\n", {})):
            with self.subTest(body=body):
                paths.wp_file(wid).write_text(f"BG={wid}\n{body}", encoding="utf-8")
                _engine_wid, args = resolve.resolve_show_args(wid)
                self.assertEqual({k: args[k] for k in ("ssfactor", "clampcomposites") if k in args}, want)
                self.assertNotIn("res", args)

    def test_clamp_text_that_is_not_a_number_reads_as_the_inherit_marker(self) -> None:
        for wid, body, want in (("311", "SSFACTOR=abc\n", {}),
                                ("312", "RENDER_RESOLUTION=sharpfx\nSSFACTOR=abc\n", {"clampcomposites": 0.0})):
            with self.subTest(body=body):
                paths.wp_file(wid).write_text(f"BG={wid}\n{body}", encoding="utf-8")
                self.assertEqual(wp.load_set(wid)["SSFACTOR"], "")
                self.assertEqual(wp.clamp_values(None, wid)["SSFACTOR"], (None, "inherit"))
                _engine_wid, args = resolve.resolve_show_args(wid)
                self.assertEqual({k: args[k] for k in ("ssfactor", "clampcomposites") if k in args}, want)

    def test_presence_stays_raw_and_a_revert_restores_absence(self) -> None:
        from lwe_ui.wp_session import SESSION
        body = "BG=401\nRENDER_RESOLUTION=sharpfx\n"
        paths.wp_file("401").write_text(body, encoding="utf-8")
        self.assertFalse(set(C.CLAMP_KEYS) & set(wp.load_set("401")))
        SESSION.forget("401")
        self.addCleanup(SESSION.forget, "401")
        self.assertTrue(SESSION.seat("401"))
        wp.update_set("401", {"SSFACTOR": 2.0})
        SESSION.mark("401", ["SSFACTOR"])
        changes = SESSION.revert_changes("401")
        self.assertEqual(changes, {"SSFACTOR": None})
        wp.update_set("401", changes)
        self.assertEqual(self._text(paths.wp_file("401")), body)

    def test_an_unset_follows_the_global_again_or_goes_back_to_1(self) -> None:
        for wid, body, after in (("501", "RENDER_RESOLUTION=sharpfx\nSSFACTOR=2\n", "RENDER_RESOLUTION=sharpfx\nSSFACTOR=\n"),
                                 ("502", "SSFACTOR=2\n", "")):
            with self.subTest(body=body):
                paths.wp_file(wid).write_text(f"BG={wid}\n{body}", encoding="utf-8")
                wp.update_set(wid, wp.clamp_unset_changes(wp.load_set(wid), "SSFACTOR"))
                self.assertEqual(self._text(paths.wp_file(wid)), f"BG={wid}\n{after}")
        self._settings("RENDER_RESOLUTION=sharpfx\nSSFACTOR=2\nCLAMPCOMPOSITES=3\n")
        for key in C.CLAMP_KEYS:
            settings.modify(lambda current, key=key: settings.clamp_unset_changes(current, key))
        self.assertEqual(self._text(paths.settings_file()), "RENDER_RESOLUTION=sharpfx\nCLAMPCOMPOSITES=1.0\n")

    def test_the_clean_up_keeps_the_empty_markers_and_a_save_writes_none(self) -> None:
        paths.wp_file("601").write_text("BG=601\nSSFACTOR=\nCLAMPCOMPOSITES=\nSPEED=1.0\n", encoding="utf-8")
        self.assertEqual(wp.sparsify_overrides(), {"601": ["SPEED"]})
        self.assertEqual(self._text(paths.wp_file("601")), "BG=601\nSSFACTOR=\nCLAMPCOMPOSITES=\n")
        self.assertEqual({k: wp.load_set("601").get(k) for k in C.CLAMP_KEYS}, {"SSFACTOR": "", "CLAMPCOMPOSITES": ""})
        paths.wp_file("602").write_text("BG=602\nRENDER_RESOLUTION=sharpfx\n", encoding="utf-8")
        text = wp.serialize(wp.load("602"), "602")
        for key in C.CLAMP_KEYS:
            self.assertNotIn(key, text)

    def test_the_restore_reads_a_clamp_value_through_migrate(self) -> None:
        spec = C.WP_SCHEMA["SSFACTOR"]
        self.assertEqual(migrate.coerce(spec, "", dense=False), ("ok", "", ""))
        self.assertEqual(migrate.coerce(spec, "2.5", dense=False), ("ok", "2.5", ""))
        self.assertEqual(migrate.coerce(spec, "5", dense=False), ("clamp", 4.0, ""))
        self.assertEqual(migrate.coerce(spec, "-1", dense=False), ("clamp", 0.0, ""))
        self.assertEqual(migrate.coerce(spec, "abc", dense=False), ("preserve", "abc", "not a number"))

    def test_the_push_rows_treat_the_pair_as_restart_settings_and_build_keys(self) -> None:
        from test_change_runner import Recorder, sent, status
        self.assertEqual({k: push.SETTING_ROWS[k] for k in C.CLAMP_KEYS}, dict.fromkeys(C.CLAMP_KEYS, "restart"))
        self.assertEqual({k: push.WP_ROWS[k] for k in C.CLAMP_KEYS}, dict.fromkeys(C.CLAMP_KEYS, "wp_build"))
        settings.save(settings.load())
        playlists.save("main", {"NAME": "Main", "MODE": "shuffle", "INTERVAL": 900, "UNIT": "min", "MEMBERS": "111"})
        settings.update({"ACTIVE_PLAYLIST": "main"})
        wp.write_keys("111", {"BG": "111"})
        writes: list = []
        with mock.patch.object(daemon_unit, "write_env", lambda *a, **k: writes.append(1) or "written"):
            rec = Recorder(status())
            with mock.patch.object(push, "api_client", rec):
                outcome = push.run_change(("settings",), lambda: settings.update({"SSFACTOR": 2.0}),
                                          [(push.SETTING_ROWS["SSFACTOR"], "SSFACTOR")])
            self.assertEqual((outcome.kind, outcome.env, len(writes)), ("applied", "written", 1))
            self.assertEqual(sent(rec), [])
            self.assertIsNone(marker.read()["generation"])
            rec = Recorder(status(current="111", speed=0.0))
            with mock.patch.object(push, "api_client", rec):
                push.run_change(("overrides",), lambda: wp.update_set("111", {"SSFACTOR": 1.5}),
                                [(push.WP_ROWS["SSFACTOR"], "SSFACTOR")], wid="111")
        requests = [(verb, args, kwargs) for verb, args, kwargs in rec.calls if verb != "status"]
        self.assertEqual(sent(rec)[0], ("playlist_set", "main"))
        shows = [kwargs for verb, _args, kwargs in requests if verb == "show"]
        self.assertEqual([kw.get("ssfactor") for kw in shows], [1.5], "one re-show carrying the number")
        speeds = [args[0] for verb, args, _kw in requests if verb == "set_speed"]
        self.assertTrue(speeds and all(value == 0 for value in speeds), f"the freeze is kept: {speeds}")


if __name__ == "__main__":
    unittest.main(verbosity=2)
