"""The fixed help screens, byte for byte, and the two headers of the debugging switch list: the
engine's own, before its first switch row (ENGINE_DEBUG_HEADER), and the one lwe help --debug
prints in its place (DEBUG_HEADER)."""

MAIN = (
    "Usage: lwe <command> [value]\n"
    "\n"
    "Everyday\n"
    "  status                            what is on screen, the timer and the version\n"
    "  show <wallpaper>                  one wallpaper on every screen now\n"
    "  next, prev                        step forward or back\n"
    "  pause [on|off|toggle]             hold or resume the playlist timer\n"
    "  off, on                           take the wallpaper off the screens, or put it back\n"
    "  playlist [<playlist>]             list your playlists, or switch to one\n"
    "  schedule ...                      day and night playlists; help schedule shows how\n"
    "\n"
    "Settings  (a name alone shows how to use it)\n"
    "  volume <0-128|+N|-N>              wallpaper sound\n"
    "  mute <on|off|toggle>              silence every wallpaper\n"
    "  mouse <on|off|toggle>             off stops every wallpaper following the pointer\n"
    "  parallax <on|off|toggle>          off stops the depth shift everywhere\n"
    "  audioreactive <on|off|toggle>     off stops every wallpaper reacting to sound\n"
    "  speed <0.1-10|0>                  animation speed; 0 freezes, not saved; speed load brings it back\n"
    "  order <shuffle|sequential|static> how the playlist moves on\n"
    "  interval <20m|30s|1h>             how long each wallpaper stays up\n"
    "  fps <1-480>                       frames per second\n"
    "  resclamp <0-4>                    cap on scene size, in screens; 0 is no cap\n"
    "  effectclamp <0-4>                 the same cap for glow and blur layers\n"
    "  <setting> load                    put one value back to what your files say\n"
    "  get <setting>...                  bare values for scripts and bars\n"
    "\n"
    "Library\n"
    "  list [scene|video|web]            your library, numbered\n"
    "  workshop                          downloads not in your library yet, numbered\n"
    "  scan                              look for new downloads now\n"
    "  add <wallpaper>...                into the pool; --playlist <playlist> also puts it in that\n"
    "                                    playlist\n"
    "  remove <wallpaper>... --playlist <playlist>\n"
    "                                    take it out of that playlist\n"
    "  trash <wallpaper>...              out of the pool; untrash lets it back in\n"
    "  compress <wallpaper>...           build the fast textures\n"
    "  bench <wallpaper>                 a test window, then its log summary\n"
    "  wallpaper <wallpaper> ...         one wallpaper's own settings, alias, properties, objects\n"
    "\n"
    "Setup\n"
    "  config [<setting> [value]]        every setting, its value and where it came from\n"
    "  reload                            check every file, print what changed, apply\n"
    "  backup export|import|preview <file>\n"
    "                                    save, restore or preview a backup\n"
    "  service [start|stop|restart]      the wallpaper service; service autostart on|off\n"
    "  debug <switch> <value>            unsupported debugging switches; help --debug lists them\n"
    "\n"
    "Pick a wallpaper by its number in a list, its Workshop id, @alias, its title in quotes,\n"
    "or current for the one on screen.\n"
    "help <command> explains one. help files lists the files you edit. help --all lists every setting.\n"
)

RESCLAMP = (
    "resclamp <0-4>\n"
    "\n"
    "Caps the size a scene is drawn at, as a multiple of your largest screen.\n"
    "Lower saves video memory. It never enlarges anything, and turning it off\n"
    "can remove blur this cap caused. Decimals work; 0 or below means no cap.\n"
    "\n"
    "Default 1. Takes effect at the next service restart, or at the next show\n"
    "for one wallpaper. effectclamp is the same cap for glow, blur and other\n"
    "effect layers, set on its own.\n"
    "\n"
    "One wallpaper:  wallpaper <wallpaper> resclamp 0\n"
    "\n"
    "Examples:\n"
    "  resclamp 0          no cap: draw at the artwork's full size\n"
    "  resclamp 1.5        up to one and a half screens\n"
    "  resclamp load       back to what your files say\n"
    "  get resclamp        print the current value\n"
    "\n"
    "Also found by: resolution, sharpness, blur, video memory.\n"
)

ALL = (
    "Every setting: its values, its default, and the engine name it points to.\n"
    "\n"
    "  order                       shuffle | sequential | static. Default shuffle. Points to playlist\n"
    "                              MODE.\n"
    "  interval                    20 | 30s | 20m | 1h  (a bare number is minutes). Default 15m. Points\n"
    "                              to playlist INTERVAL, in seconds.\n"
    "  playlist                    a playlist's number or name. Default none. Points to ACTIVE_PLAYLIST.\n"
    "  volume                      0 to 128, +N, -N. Default 15. Points to ENGINE_VOLUME, VOLUME.\n"
    "  mute                        on | off | toggle. Default off. Points to OVERRIDE_MUTE.\n"
    "  audioreactive               on | off | toggle. Default on. Points to OVERRIDE_AUDIO_OFF.\n"
    "  mouse                       on | off | toggle. Default on. Points to OVERRIDE_MOUSE_OFF.\n"
    "  parallax                    on | off | toggle. Default on. Points to OVERRIDE_PARALLAX_OFF.\n"
    "  config audioreactivedefault on | off. Default off. Points to AUDIO_REACTIVE_DEFAULT.\n"
    "  config mousedefault         on | off. Default off. Points to MOUSE_DEFAULT.\n"
    "  config parallaxdefault      on | off. Default on. Points to PARALLAX_DEFAULT.\n"
    "  automute                    on | off | toggle. Default on. Points to AUTOMUTE_DEFAULT, AUTOMUTE.\n"
    "  particles                   on | off | toggle. Default on. Points to PARTICLES_DEFAULT.\n"
    "  fps                         1 to 480, a whole number. Default 60. Points to ENGINE_FPS.\n"
    "  speed                       0.1 to 10  (1 is normal; 0 freezes it and is not saved). Default 1.\n"
    "                              Points to ENGINE_TIMESCALE, SPEED, LWE_TIMESCALE.\n"
    "  scaling                     default | stretch | fit | fill. Default default. Points to\n"
    "                              ENGINE_SCALING, SCALING.\n"
    "  edge                        extend | blank | tile. Default extend. Points to ENGINE_CLAMP,\n"
    "                              CLAMPING: clamp | border | repeat.\n"
    "  fullscreen                  keep | pause | stop. Default your older pause settings, until you\n"
    "                              choose. Points to FULLSCREEN_BEHAVIOR: off | pause | stop; per\n"
    "                              wallpaper FULLSCREEN_PAUSE.\n"
    "  layer                       background | bottom | top | overlay. Default bottom. Points to\n"
    "                              ENGINE_LAYER.\n"
    "  resclamp                    0 to 4, decimals allowed  (1 is your screen size; 0 or below is no\n"
    "                              cap). Default 1. Points to SSFACTOR (RENDER_RESOLUTION is still read\n"
    "                              from older files), LWE_SSFACTOR.\n"
    "  effectclamp                 0 to 4, decimals allowed  (1 is your screen size; 0 or below is no\n"
    "                              cap). Default 1. Points to CLAMPCOMPOSITES (RENDER_RESOLUTION is still\n"
    "                              read from older files), LWE_CLAMPCOMPOSITES.\n"
    "  texturecache                on | off | toggle. Default on. Points to ENGINE_TEXCOMP, TEXCOMP,\n"
    "                              LWE_TEXCOMP.\n"
    "  texturedetail               auto | full. Default auto. Points to TEXTURE_DETAIL, LWE_TEXDETAIL.\n"
    "  videodecode                 software | auto. Default software. Points to ENGINE_HWDEC: no | auto,\n"
    "                              LWE_HWDEC.\n"
    "  reviewrequired              on | off | toggle. Default on. Points to REVIEW_REQUIRED.\n"
    "  storage                     copy | reference. Default copy. Points to STORAGE_POLICY.\n"
    "  detect                      manual | launch | timer | watch. Default watch. Points to DETECT_MODE:\n"
    "                              manual | launch | interval | watch.\n"
    "  detectevery                 15s to 24h  (a bare number is seconds). Default 60s. Points to\n"
    "                              DETECT_INTERVAL_SEC.\n"
    "  libraryfolder               a folder. Default none. Points to WALLPAPERS_DIR.\n"
    "  workshopfolder              a folder. Default found automatically. Points to WORKSHOP_DIR.\n"
    "  steamfolder                 a folder. Default found automatically. Points to STEAM_DIR.\n"
    "  assetsfolder                a folder. Default found automatically. Points to ASSETS_DIR.\n"
    "  lightdimming                0.01 to 1000  (higher is dimmer). Default 0.7. Points to\n"
    "                              ENGINE_CLASSIC_K, CLASSIC_K, LWE_CLASSICK.\n"
    "  lightfalloff                0.5 to 6. Default 2.6. Points to ENGINE_CLASSIC_EXP, CLASSIC_EXP,\n"
    "                              LWE_CLASSICEXP.\n"
    "  audiogain                   0.1 to 20. Default 3. Points to ENGINE_AUDIO_GAIN, AUDIO_GAIN,\n"
    "                              LWE_AUDIOGAIN.\n"
    "  audiosmoothing              0 to 500 ms  (a bare number is milliseconds; 0 is off). Default 90.\n"
    "                              Points to LWE_AUDIOSMOOTH.\n"
    "  watchdog                    0 to 24h  (a bare number is seconds; 0 is off). Default 300. Points to\n"
    "                              LWE_DEADMAN.\n"
    "  color                       one quoted value: \"brightness contrast saturation hue\", hue in\n"
    "                              degrees. Default \"1 1 1 0\". Points to LWE_CC.\n"
    "  wallpaper <w> zoom          1 to 2. Points to FIT_ZOOM.\n"
    "  wallpaper <w> panx          -1 to 1. Points to FIT_PAN_X.\n"
    "  wallpaper <w> pany          -1 to 1. Points to FIT_PAN_Y.\n"
    "  wallpaper <w> brightness    0 to 4  (1 is normal). Points to CC.\n"
    "  wallpaper <w> contrast      0 to 4  (1 is normal). Points to CC.\n"
    "  wallpaper <w> saturation    0 to 4  (1 is normal). Points to CC.\n"
    "  wallpaper <w> hue           -180 to 180 degrees. Points to CC, stored in radians.\n"
    "  wallpaper <w> fullscreen    on | off | inherit. Points to FULLSCREEN_PAUSE.\n"
    "  wallpaper <w> property      property <name> <value>. Points to PROP_<name>.\n"
    "  wallpaper <w> hide / unhide hide <object id> | unhide <object id>. Points to SKIP.\n"
    "  wallpaper <w> alias         alias <name>. Points to ALIAS.\n"
)

SCHEDULE = (
    "  schedule                            show day and night, and whether the schedule is on\n"
    "  schedule on | off                   \n"
    "  schedule day time <time>            when day starts\n"
    "  schedule day playlist <playlist>    what plays by day\n"
    "  schedule night time <time>          when night starts\n"
    "  schedule night playlist <playlist>  what plays at night\n"
    "\n"
    "Day runs from its start time until night starts; night runs until day starts.\n"
    "Times use this computer's clock: 7:30, 07:30, 730 and 0730 all mean 07:30.\n"
    "A playlist is its number from the playlist list, or its name.\n"
    "While the schedule is off you can fill it in one piece at a time. schedule on\n"
    "checks that day and night have different times and different playlists.\n"
    "A playlist you switch to by hand stays until the next start time.\n"
    "\n"
    "Example, starting from nothing:\n"
    "  playlist                            see your playlists, numbered\n"
    "  schedule day playlist 1             \n"
    "  schedule night playlist 2           \n"
    "  schedule on                         day starts at 08:00 and night at 20:00 until you change them\n"
    "\n"
    "Swapping day and night: schedule off, set both playlists, schedule on.\n"
)

FILES = (
    "Files you can edit by hand. Run reload after editing: it checks the files,\n"
    "prints what changed and applies it.\n"
    "\n"
    "In ~/.config/lwe\n"
    "  playlists/*.conf            one file per playlist: NAME, MODE, INTERVAL in seconds, UNIT, and\n"
    "                              MEMBERS, the wallpaper ids in play order. Copy a file to make a\n"
    "                              playlist, change NAME to rename it, delete the file to remove it. list\n"
    "                              prints each wallpaper's id.\n"
    "  app-condition.txt           apps that trigger the running-apps rule, one process name per line, up\n"
    "                              to 15 characters\n"
    "  pause-blacklist.txt         fullscreen apps that never cause a pause, one app id per line\n"
    "  settings.conf               the schedule as SCHEDULE=\"07:30=ocean;20:00=calm\" and\n"
    "                              SCHEDULE_ENABLED=true, day first, using playlist file names\n"
    "  wp/<id>.conf                one wallpaper's own values\n"
    "\n"
    "In ~/.local/state/lwe\n"
    "  panel/records/<id>.jsonl    a wallpaper's history, one event per line; read only\n"
    "\n"
    "A hand edit is safe unless the panel saves the same file at that same moment.\n"
)

DEBUG_HEADER = (
    "Unsupported debugging switches. They can change or disappear in any release.\n"
    "Set one:       debug <switch> <value>   (takes effect at the next service start)\n"
    "Turn one off:  debug unset <switch>\n"
    "Each name is an alias; the engine's own variable still works.\n"
    "\n"
)

ENGINE_DEBUG_HEADER = (
    "Unsupported debugging switches. They can change or disappear in any release.\n"
    "Set one at launch with --debug <switch>=<value>; repeat it for more.\n"
    "Each name is an alias; the engine's own variable still works.\n"
    "\n"
)
