"""The command, setting and per-wallpaper rows in page order, as data with no logic.

COMMANDS rows hold grp, name, form, what and note; SETTINGS rows hold name, typed, values, default,
engine, scope, when, what and ptr; PER_WALLPAPER rows hold name, values, default, what and ptr.
"""
from __future__ import annotations

COMMANDS: tuple[dict[str, str], ...] = (
    {
        "grp": "Running",
        "name": "status",
        "form": "status",
        "what": "What is on screen, the playlist timer, the version and a settings summary.",
        "note": "",
    },
    {
        "grp": "Running",
        "name": "lwe",
        "form": "lwe",
        "what": "lwe with nothing after it prints the same as status.",
        "note": "",
    },
    {
        "grp": "Running",
        "name": "show",
        "form": "show <wallpaper>",
        "what": "Puts one wallpaper on every screen now, with its own saved settings, and prints what it picked, for example 2 = Deep Space (1505438974).",
        "note": "",
    },
    {
        "grp": "Running",
        "name": "next",
        "form": "next",
        "what": "Goes to the next wallpaper.",
        "note": "",
    },
    {
        "grp": "Running",
        "name": "prev",
        "form": "prev",
        "what": "Goes back to the wallpaper before this one.",
        "note": "",
    },
    {
        "grp": "Running",
        "name": "pause",
        "form": "pause [on|off|toggle]",
        "what": "Pauses the playlist timer; pause off resumes it; toggle flips it, for a keybind. The animation keeps moving; speed 0 freezes it.",
        "note": "",
    },
    {
        "grp": "Running",
        "name": "off",
        "form": "off",
        "what": "Takes the wallpaper off every screen without stopping the service.",
        "note": "",
    },
    {
        "grp": "Running",
        "name": "on",
        "form": "on",
        "what": "Puts the wallpaper back on every screen.",
        "note": "",
    },
    {
        "grp": "Service",
        "name": "service",
        "form": "service",
        "what": "Whether the service is running, whether it starts at login, its memory use, and the command that shows its log.",
        "note": "",
    },
    {
        "grp": "Service",
        "name": "service start",
        "form": "service start",
        "what": "Starts the service now. Autostart stays as it is.",
        "note": "",
    },
    {
        "grp": "Service",
        "name": "service stop",
        "form": "service stop",
        "what": "Stops the service now. Autostart stays as it is.",
        "note": "",
    },
    {
        "grp": "Service",
        "name": "service restart",
        "form": "service restart",
        "what": "Restarts the service, which applies the settings marked restart.",
        "note": "",
    },
    {
        "grp": "Service",
        "name": "service autostart",
        "form": "service autostart on|off",
        "what": "Whether the service starts when you log in. It does not start or stop it now.",
        "note": "",
    },
    {
        "grp": "Playlists",
        "name": "playlist",
        "form": "playlist [list]",
        "what": "Lists your playlists, numbered, sorted by name.",
        "note": "",
    },
    {
        "grp": "Playlists",
        "name": "playlist <playlist>",
        "form": "playlist <playlist>",
        "what": "Switches to a playlist, by its number in that list or its name. To make, rename, delete or fill playlists, edit their files (see Files).",
        "note": "",
    },
    {
        "grp": "Schedule",
        "name": "schedule",
        "form": "schedule",
        "what": "Shows day and night: each start time and playlist, whether the schedule is on, and whether it is day or night now.",
        "note": "",
    },
    {
        "grp": "Schedule",
        "name": "schedule on|off",
        "form": "schedule on|off",
        "what": "Turns the schedule on or off. On checks that day and night have different times and different playlists; off keeps everything you set.",
        "note": "",
    },
    {
        "grp": "Schedule",
        "name": "schedule day time",
        "form": "schedule day time <time>",
        "what": "When day starts. 7:30, 07:30, 730 and 0730 all mean 07:30.",
        "note": "",
    },
    {
        "grp": "Schedule",
        "name": "schedule day playlist",
        "form": "schedule day playlist <playlist>",
        "what": "The playlist that plays by day, by its number in the playlist list or its name.",
        "note": "",
    },
    {
        "grp": "Schedule",
        "name": "schedule night time",
        "form": "schedule night time <time>",
        "what": "When night starts.",
        "note": "",
    },
    {
        "grp": "Schedule",
        "name": "schedule night playlist",
        "form": "schedule night playlist <playlist>",
        "what": "The playlist that plays at night.",
        "note": "",
    },
    {
        "grp": "Library",
        "name": "list",
        "form": "list [scene|video|web]",
        "what": "Your library, numbered by title, with each wallpaper's id and alias. A list of one type keeps the full list's numbers.",
        "note": "",
    },
    {
        "grp": "Library",
        "name": "workshop",
        "form": "workshop",
        "what": "Workshop downloads that are not in your pool yet, numbered, including ones waiting for review.",
        "note": "",
    },
    {
        "grp": "Library",
        "name": "scan",
        "form": "scan",
        "what": "Looks for new Workshop downloads now.",
        "note": "",
    },
    {
        "grp": "Library",
        "name": "add",
        "form": "add <wallpaper>...",
        "what": "Brings wallpapers into the pool: checks them, compresses them and registers them. A wallpaper waiting for review is approved.",
        "note": "",
    },
    {
        "grp": "Library",
        "name": "add --playlist",
        "form": "add <wallpaper>... --playlist <playlist>",
        "what": "Also appends each wallpaper to the end of that playlist, and never takes it out of another; repeat --playlist for more than one. Works on a wallpaper already in the pool. Already in that playlist: nothing changes and it says so. An unknown playlist: nothing changes at all.",
        "note": "",
    },
    {
        "grp": "Library",
        "name": "remove --playlist",
        "form": "remove <wallpaper>... --playlist <playlist>",
        "what": "Takes wallpapers out of that playlist; repeat --playlist for more than one. It only ever touches playlists: without --playlist it refuses and points to trash. Not in that playlist: nothing changes and it says so.",
        "note": "",
    },
    {
        "grp": "Library",
        "name": "compress",
        "form": "compress <wallpaper>... | --all",
        "what": "Builds the compressed textures that make wallpapers load faster and use less video memory. Prints one line per wallpaper with its texture memory before and after, then, for more than one, a line with how many were compressed, the totals, and the disk space the cache adds. The originals stay on disk.",
        "note": "",
    },
    {
        "grp": "Library",
        "name": "bench",
        "form": "bench <wallpaper>",
        "what": "Opens a test window beside your wallpaper and prints its log summary when you close it.",
        "note": "",
    },
    {
        "grp": "Library",
        "name": "trash",
        "form": "trash <wallpaper>...",
        "what": "Takes wallpapers out of the pool: deletes LWE's own copy if it made one and stops them being imported again. The Steam download is left alone.",
        "note": "",
    },
    {
        "grp": "Library",
        "name": "untrash",
        "form": "untrash [<wallpaper>... | --all]",
        "what": "Lifts that block so a wallpaper can be imported again; it does not bring deleted files back. Alone, it lists the trash, numbered.",
        "note": "",
    },
    {
        "grp": "One wallpaper",
        "name": "wallpaper",
        "form": "wallpaper <wallpaper>",
        "what": "One wallpaper's details: title, id, alias, its own settings and its Workshop link.",
        "note": "",
    },
    {
        "grp": "One wallpaper",
        "name": "wallpaper ... setting",
        "form": "wallpaper <wallpaper> <setting> [value]",
        "what": "Reads or sets one wallpaper's own setting; a change is saved and applied at once.",
        "note": "",
    },
    {
        "grp": "One wallpaper",
        "name": "wallpaper ... unset",
        "form": "wallpaper <wallpaper> unset <setting>",
        "what": "Removes the wallpaper's own value, so it follows the global setting again.",
        "note": "",
    },
    {
        "grp": "One wallpaper",
        "name": "wallpaper ... alias",
        "form": "wallpaper <wallpaper> alias <name>",
        "what": "Gives a wallpaper a short name you can use as @name.",
        "note": "",
    },
    {
        "grp": "One wallpaper",
        "name": "wallpaper ... properties",
        "form": "wallpaper <wallpaper> properties",
        "what": "Lists the knobs the wallpaper's author added, with their values and choices. A value marked "
                "(yours) is set in the wallpaper's own file, which includes the values an import copied from a "
                "preset. Replaces the name props.",
        "note": "",
    },
    {
        "grp": "One wallpaper",
        "name": "wallpaper ... objects",
        "form": "wallpaper <wallpaper> objects [<filter>]",
        "what": "Lists the wallpaper's parts as a tree: each part's id, type and name, and whether its author or you hid it. It reads the wallpaper's files, so it works for any wallpaper. A filter word narrows it: a type such as particle, or part of a name such as rain. "
                "The depth comes from a walk that shows a part whose parent is missing, or that repeats in a "
                "parent cycle, as a root, while -j's parent still names the parent the scene gives.",
        "note": "",
    },
    {
        "grp": "One wallpaper",
        "name": "wallpaper ... blink",
        "form": "wallpaper <wallpaper> blink <id>",
        "what": "Hides that part for two seconds and brings it back, so you can see which part it is. Needs the wallpaper on screen.",
        "note": "",
    },
    {
        "grp": "Settings",
        "name": "get",
        "form": "get <setting> [<setting>...]",
        "what": "Prints bare values, one per line, for scripts and status bars.",
        "note": "",
    },
    {
        "grp": "Settings",
        "name": "config",
        "form": "config [<setting> [value]]",
        "what": "Lists every setting with its value and where it came from, or reads or sets one.",
        "note": "",
    },
    {
        "grp": "Settings",
        "name": "config unset",
        "form": "config unset <setting>",
        "what": "Removes a saved value, so the setting goes back to its default.",
        "note": "",
    },
    {
        "grp": "Settings",
        "name": "load",
        "form": "<setting> load",
        "what": "Puts one running value back to what your files say, the wallpaper's own value first.",
        "note": "",
    },
    {
        "grp": "Settings",
        "name": "reload",
        "form": "reload",
        "what": "Checks every settings file, including the ones you edit by hand, prints what changed, and applies it.",
        "note": "",
    },
    {
        "grp": "Settings",
        "name": "backup",
        "form": "backup export|import|preview <file>",
        "what": "Saves, restores or previews a settings backup.",
        "note": "",
    },
    {
        "grp": "Debugging",
        "name": "debug",
        "form": "debug <switch> <value>",
        "what": "Sets one debugging switch by its plain name, for the next service start. debug <switch> alone shows how to use it.",
        "note": "",
    },
    {
        "grp": "Debugging",
        "name": "debug unset",
        "form": "debug unset <switch>",
        "what": "Turns a debugging switch back to its default.",
        "note": "",
    },
    {
        "grp": "Help",
        "name": "help",
        "form": "help [<command>]",
        "what": "Lists the commands, or explains one command, setting or group.",
        "note": "",
    },
    {
        "grp": "Help",
        "name": "help --all",
        "form": "help --all",
        "what": "Every setting with its values, its default and the engine name it points to.",
        "note": "",
    },
    {
        "grp": "Help",
        "name": "help files",
        "form": "help files",
        "what": "The files you can edit by hand, and what each holds.",
        "note": "",
    },
    {
        "grp": "Help",
        "name": "help --debug",
        "form": "help --debug",
        "what": "The unsupported debugging switches.",
        "note": "",
    },
)

SETTINGS: tuple[dict[str, str], ...] = (
    {
        "name": "order",
        "typed": "",
        "values": "shuffle | sequential | static",
        "default": "shuffle",
        "engine": "",
        "scope": "the active playlist",
        "when": "now",
        "what": "How the playlist moves on; static never changes.",
        "ptr": "playlist MODE",
    },
    {
        "name": "interval",
        "typed": "",
        "values": "20 | 30s | 20m | 1h  (a bare number is minutes)",
        "default": "15m",
        "engine": "",
        "scope": "the active playlist",
        "when": "now",
        "what": "How long each wallpaper stays up.",
        "ptr": "playlist INTERVAL, in seconds",
    },
    {
        "name": "playlist",
        "typed": "",
        "values": "a playlist's number or name",
        "default": "",
        "engine": "",
        "scope": "global",
        "when": "now",
        "what": "Which playlist plays.",
        "ptr": "ACTIVE_PLAYLIST",
    },
    {
        "name": "volume",
        "typed": "",
        "values": "0 to 128, +N, -N",
        "default": "15",
        "engine": "",
        "scope": "global and per wallpaper",
        "when": "now",
        "what": "Wallpaper sound.",
        "ptr": "ENGINE_VOLUME, VOLUME",
    },
    {
        "name": "mute",
        "typed": "",
        "values": "on | off | toggle",
        "default": "off",
        "engine": "",
        "scope": "every wallpaper, until switched back; the panel clears it when it quits",
        "when": "now",
        "what": "Silences every wallpaper.",
        "ptr": "OVERRIDE_MUTE",
    },
    {
        "name": "audioreactive",
        "typed": "",
        "values": "on | off | toggle",
        "default": "on",
        "engine": "",
        "scope": "every wallpaper, until switched back; the panel clears it when it quits",
        "when": "now",
        "what": "off stops every wallpaper reacting to sound; on lets each wallpaper decide.",
        "ptr": "OVERRIDE_AUDIO_OFF",
    },
    {
        "name": "mouse",
        "typed": "",
        "values": "on | off | toggle",
        "default": "on",
        "engine": "",
        "scope": "every wallpaper, until switched back; the panel clears it when it quits",
        "when": "now",
        "what": "off stops every wallpaper following the pointer; on lets each wallpaper decide.",
        "ptr": "OVERRIDE_MOUSE_OFF",
    },
    {
        "name": "parallax",
        "typed": "",
        "values": "on | off | toggle",
        "default": "on",
        "engine": "",
        "scope": "every wallpaper, until switched back; the panel clears it when it quits",
        "when": "now",
        "what": "off stops the depth shift on every wallpaper; on lets each wallpaper decide.",
        "ptr": "OVERRIDE_PARALLAX_OFF",
    },
    {
        "name": "audioreactivedefault",
        "typed": "config audioreactivedefault <on|off>",
        "values": "on | off",
        "default": "off",
        "engine": "",
        "scope": "global",
        "when": "now",
        "what": "Whether wallpapers with no setting of their own react to sound.",
        "ptr": "AUDIO_REACTIVE_DEFAULT",
    },
    {
        "name": "mousedefault",
        "typed": "config mousedefault <on|off>",
        "values": "on | off",
        "default": "off",
        "engine": "",
        "scope": "global",
        "when": "now",
        "what": "Whether wallpapers with no setting of their own follow the pointer.",
        "ptr": "MOUSE_DEFAULT",
    },
    {
        "name": "parallaxdefault",
        "typed": "config parallaxdefault <on|off>",
        "values": "on | off",
        "default": "on",
        "engine": "",
        "scope": "global",
        "when": "now",
        "what": "Whether wallpapers with no setting of their own shift with depth.",
        "ptr": "PARALLAX_DEFAULT",
    },
    {
        "name": "automute",
        "typed": "",
        "values": "on | off | toggle",
        "default": "on",
        "engine": "",
        "scope": "global and per wallpaper",
        "when": "next wallpaper",
        "what": "Goes quiet while another app plays sound.",
        "ptr": "AUTOMUTE_DEFAULT, AUTOMUTE",
    },
    {
        "name": "particles",
        "typed": "",
        "values": "on | off | toggle",
        "default": "on",
        "engine": "",
        "scope": "global",
        "when": "now",
        "what": "Smoke, sparks, rain and similar effects. May rebuild the wallpaper on screen.",
        "ptr": "PARTICLES_DEFAULT",
    },
    {
        "name": "fps",
        "typed": "",
        "values": "1 to 480, a whole number",
        "default": "60",
        "engine": "30",
        "scope": "global",
        "when": "now",
        "what": "Frames per second; lower saves power.",
        "ptr": "ENGINE_FPS",
    },
    {
        "name": "speed",
        "typed": "",
        "values": "0.1 to 10  (1 is normal; 0 freezes it and is not saved)",
        "default": "1",
        "engine": "",
        "scope": "global and per wallpaper",
        "when": "now",
        "what": "How fast scene animation runs. speed 0 freezes it without saving; speed load brings back the saved speed. A wallpaper's own speed replaces the global one.",
        "ptr": "ENGINE_TIMESCALE, SPEED, LWE_TIMESCALE",
    },
    {
        "name": "scaling",
        "typed": "",
        "values": "default | stretch | fit | fill",
        "default": "default",
        "engine": "",
        "scope": "global and per wallpaper",
        "when": "next wallpaper",
        "what": "How the picture fits your screen. default lets the engine decide from the screen and the picture; fit shows all of it; fill covers the screen and may crop; stretch fills it and may distort.",
        "ptr": "ENGINE_SCALING, SCALING",
    },
    {
        "name": "edge",
        "typed": "",
        "values": "extend | blank | tile",
        "default": "extend",
        "engine": "",
        "scope": "global and per wallpaper",
        "when": "next wallpaper",
        "what": "What shows past the picture's edge: the edge pixels stretched, nothing, or the picture repeated.",
        "ptr": "ENGINE_CLAMP, CLAMPING: clamp | border | repeat",
    },
    {
        "name": "fullscreen",
        "typed": "",
        "values": "keep | pause | stop",
        "default": "your older pause settings, until you choose",
        "engine": "",
        "scope": "global; a wallpaper can opt out",
        "when": "now",
        "what": "What happens while a game or app is fullscreen: keep playing, pause, or stop and free the screens; stop frees the screens only on the Wayland desktop and pauses elsewhere. One wallpaper: wallpaper <wallpaper> fullscreen on | off | inherit, where off means it keeps playing.",
        "ptr": "FULLSCREEN_BEHAVIOR: off | pause | stop; per wallpaper FULLSCREEN_PAUSE",
    },
    {
        "name": "layer",
        "typed": "",
        "values": "background | bottom | top | overlay",
        "default": "bottom",
        "engine": "",
        "scope": "global",
        "when": "restart",
        "what": "Which desktop layer the wallpaper sits on, for compositors such as niri. top and overlay sit over your windows; layer bottom puts it back.",
        "ptr": "ENGINE_LAYER",
    },
    {
        "name": "resclamp",
        "typed": "",
        "values": "0 to 4, decimals allowed  (1 is your screen size; 0 or below is no cap)",
        "default": "1",
        "engine": "",
        "scope": "global and per wallpaper",
        "when": "restart, or the next show for one wallpaper",
        "what": "Caps the size a scene is drawn at, as a multiple of your largest screen. Lower saves video memory. It never enlarges anything; turning it off can remove blur this cap caused.",
        "ptr": "a new saved setting (RENDER_RESOLUTION stays the fallback for old files), LWE_SSFACTOR",
    },
    {
        "name": "effectclamp",
        "typed": "",
        "values": "0 to 4, decimals allowed  (1 is your screen size; 0 or below is no cap)",
        "default": "1",
        "engine": "",
        "scope": "global and per wallpaper",
        "when": "restart, or the next show for one wallpaper",
        "what": "The same cap for glow, blur and the other effect layers, set on its own.",
        "ptr": "a new saved setting (RENDER_RESOLUTION stays the fallback for old files), LWE_CLAMPCOMPOSITES",
    },
    {
        "name": "texturecache",
        "typed": "",
        "values": "on | off | toggle",
        "default": "on",
        "engine": "",
        "scope": "global and per wallpaper",
        "when": "restart, or the next show for one wallpaper",
        "what": "Uses the compressed textures that compress builds; off loads the originals and deletes nothing.",
        "ptr": "ENGINE_TEXCOMP, TEXCOMP, LWE_TEXCOMP",
    },
    {
        "name": "texturedetail",
        "typed": "",
        "values": "auto | full",
        "default": "auto",
        "engine": "",
        "scope": "global and per wallpaper",
        "when": "restart, or the next show for one wallpaper",
        "what": "auto loads smaller textures when your screen does not need the full size; full always loads everything.",
        "ptr": "TEXTURE_DETAIL, LWE_TEXDETAIL",
    },
    {
        "name": "videodecode",
        "typed": "",
        "values": "software | auto",
        "default": "software",
        "engine": "",
        "scope": "global",
        "when": "restart",
        "what": "How video wallpapers are decoded; auto uses the graphics card when it can.",
        "ptr": "ENGINE_HWDEC: no | auto, LWE_HWDEC",
    },
    {
        "name": "reviewrequired",
        "typed": "",
        "values": "on | off | toggle",
        "default": "on",
        "engine": "",
        "scope": "global",
        "when": "next download",
        "what": "Downloads the panel finds by itself wait for your review. add always brings a wallpaper in. Replaces the name review.",
        "ptr": "REVIEW_REQUIRED",
    },
    {
        "name": "storage",
        "typed": "",
        "values": "copy | reference",
        "default": "copy",
        "engine": "",
        "scope": "global",
        "when": "next import",
        "what": "Whether the library keeps its own copy of each wallpaper or points at the Workshop folder.",
        "ptr": "STORAGE_POLICY",
    },
    {
        "name": "detect",
        "typed": "",
        "values": "manual | launch | timer | watch",
        "default": "watch",
        "engine": "",
        "scope": "global",
        "when": "now",
        "what": "How the panel finds new downloads: only when you scan, when the panel starts, on a timer, or by watching the folder. Works only while the panel is running; scan works any time.",
        "ptr": "DETECT_MODE: manual | launch | interval | watch",
    },
    {
        "name": "detectevery",
        "typed": "",
        "values": "15s to 24h  (a bare number is seconds)",
        "default": "60s",
        "engine": "",
        "scope": "global",
        "when": "now",
        "what": "How often the timer looks, when detect is timer.",
        "ptr": "DETECT_INTERVAL_SEC",
    },
    {
        "name": "libraryfolder",
        "typed": "",
        "values": "a folder",
        "default": "",
        "engine": "",
        "scope": "global",
        "when": "now",
        "what": "Where your library is kept.",
        "ptr": "WALLPAPERS_DIR",
    },
    {
        "name": "workshopfolder",
        "typed": "",
        "values": "a folder",
        "default": "found automatically",
        "engine": "",
        "scope": "global",
        "when": "now",
        "what": "Steam's Workshop download folder.",
        "ptr": "WORKSHOP_DIR",
    },
    {
        "name": "steamfolder",
        "typed": "",
        "values": "a folder",
        "default": "found automatically",
        "engine": "",
        "scope": "global",
        "when": "now",
        "what": "Steam's install folder.",
        "ptr": "STEAM_DIR",
    },
    {
        "name": "assetsfolder",
        "typed": "",
        "values": "a folder",
        "default": "found automatically",
        "engine": "",
        "scope": "global",
        "when": "restart",
        "what": "Wallpaper Engine's assets folder.",
        "ptr": "ASSETS_DIR",
    },
    {
        "name": "lightdimming",
        "typed": "",
        "values": "0.01 to 1000  (higher is dimmer)",
        "default": "0.7",
        "engine": "16",
        "scope": "global and per wallpaper",
        "when": "now",
        "what": "Overall brightness of the lights inside scenes.",
        "ptr": "ENGINE_CLASSIC_K, CLASSIC_K, LWE_CLASSICK",
    },
    {
        "name": "lightfalloff",
        "typed": "",
        "values": "0.5 to 6",
        "default": "2.6",
        "engine": "2",
        "scope": "global and per wallpaper",
        "when": "now",
        "what": "How quickly scene lights fade with distance.",
        "ptr": "ENGINE_CLASSIC_EXP, CLASSIC_EXP, LWE_CLASSICEXP",
    },
    {
        "name": "audiogain",
        "typed": "",
        "values": "0.1 to 20",
        "default": "3",
        "engine": "1",
        "scope": "global and per wallpaper",
        "when": "now",
        "what": "How strongly wallpapers react to sound.",
        "ptr": "ENGINE_AUDIO_GAIN, AUDIO_GAIN, LWE_AUDIOGAIN",
    },
    {
        "name": "audiosmoothing",
        "typed": "",
        "values": "0 to 500 ms  (a bare number is milliseconds; 0 is off)",
        "default": "90",
        "engine": "",
        "scope": "global",
        "when": "now; not saved yet, so a restart goes back to the start value",
        "what": "How smoothly the sound levels wallpapers react to change.",
        "ptr": "LWE_AUDIOSMOOTH",
    },
    {
        "name": "watchdog",
        "typed": "",
        "values": "0 to 24h  (a bare number is seconds; 0 is off)",
        "default": "300",
        "engine": "",
        "scope": "engine start",
        "when": "restart",
        "what": "Once the panel or another client has pinged the engine, if the engine then draws nothing and hears nothing for this long, it frees your screens (on the Wayland desktop; elsewhere it only logs). It does not restart anything.",
        "ptr": "LWE_DEADMAN",
    },
    {
        "name": "color",
        "typed": "",
        "values": "one quoted value: \"brightness contrast saturation hue\", hue in degrees",
        "default": "\"1 1 1 0\"",
        "engine": "",
        "scope": "engine start",
        "when": "restart",
        "what": "The color correction every wallpaper starts with when the engine runs without the panel.",
        "ptr": "LWE_CC",
    },
)

PER_WALLPAPER: tuple[dict[str, str], ...] = (
    {
        "name": "zoom",
        "values": "1 to 2",
        "default": "1",
        "what": "How far the wallpaper is zoomed in.",
        "ptr": "FIT_ZOOM",
    },
    {
        "name": "panx",
        "values": "-1 to 1",
        "default": "0",
        "what": "Moves a zoomed wallpaper left or right. A minus sign is a value, not a step.",
        "ptr": "FIT_PAN_X",
    },
    {
        "name": "pany",
        "values": "-1 to 1",
        "default": "0",
        "what": "Moves a zoomed wallpaper up or down.",
        "ptr": "FIT_PAN_Y",
    },
    {
        "name": "brightness",
        "values": "0 to 4  (1 is normal)",
        "default": "1",
        "what": "Brightness of this wallpaper.",
        "ptr": "CC",
    },
    {
        "name": "contrast",
        "values": "0 to 4  (1 is normal)",
        "default": "1",
        "what": "Contrast of this wallpaper.",
        "ptr": "CC",
    },
    {
        "name": "saturation",
        "values": "0 to 4  (1 is normal)",
        "default": "1",
        "what": "Color strength of this wallpaper.",
        "ptr": "CC",
    },
    {
        "name": "hue",
        "values": "-180 to 180 degrees",
        "default": "0",
        "what": "Shifts every color around the color wheel.",
        "ptr": "CC, stored in radians",
    },
    {
        "name": "fullscreen",
        "values": "on | off | inherit",
        "default": "inherit",
        "what": "off keeps this wallpaper playing while something is fullscreen; on makes it follow the fullscreen rule.",
        "ptr": "FULLSCREEN_PAUSE",
    },
    {
        "name": "property",
        "values": "property <name> <value>",
        "default": "",
        "what": "Sets one of the knobs the wallpaper's author added. Replaces the name prop.",
        "ptr": "PROP_<name>",
    },
    {
        "name": "hide / unhide",
        "values": "hide <object id> | unhide <object id>",
        "default": "",
        "what": "Hides or shows one part of the wallpaper, by the id objects prints.",
        "ptr": "SKIP",
    },
    {
        "name": "alias",
        "values": "alias <name>",
        "default": "",
        "what": "A short name for this wallpaper, used as @name.",
        "ptr": "ALIAS",
    },
)
